CREATE TABLE IF NOT EXISTS ssologin_user(
  uid INT NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  username VARCHAR(100) NOT NULL COMMENT '用户名',
  password VARCHAR(1024) NOT NULL COMMENT '密码摘要',
  regtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',

  PRIMARY KEY(uid),
  UNIQUE(username)

)CHARSET=utf8 AUTO_INCREMENT=10000;

CREATE TABLE IF NOT EXISTS ssologin_session(
  sid INT NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  uid INT NOT NULL COMMENT '用户ID',
  session VARCHAR(1024) NOT NULL COMMENT '用户登录态',
  ltime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间',

  PRIMARY KEY(sid),
  FOREIGN KEY(uid) REFERENCES `ssologin_user`(uid)

)CHARSET=utf8 AUTO_INCREMENT=10000;