package(default_visibility = ["//visibility:public"])

cc_library(
	name = "ssologin_crypto",
	srcs = ["ssologin_crypto.cc"],
	hdrs = ["ssologin_crypto.h"],
    deps = ["@boringssl//:crypto", "@boringssl//:ssl"],
)