CREATE TABLE IF NOT EXISTS ssologin_user(
  uid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  regtime TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ssologin_session(
  sid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  uid INTEGER NOT NULL,
  session TEXT NOT NULL,
  ltime TEXT DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY(uid) REFERENCES `ssologin_user`(uid)
);